# Generated by Django 5.2 on 2025-05-23 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=50)),
                ('encrypted_message', models.TextField()),
                ('encryption_type', models.CharField(max_length=50)),
                ('hint', models.TextField()),
                ('tutorial', models.TextField()),
                ('answer', models.CharField(max_length=255)),
                ('difficulty', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['difficulty'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lives', models.IntegerField(default=3)),
                ('current_stage', models.CharField(default='continent', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
