# Generated by Django 5.2 on 2025-05-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_stagehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_id', models.CharField(max_length=250)),
                ('stage', models.CharField(max_length=250)),
                ('answer', models.CharField(max_length=250)),
                ('encryption_type', models.CharField(max_length=250)),
                ('hint', models.CharField(max_length=250)),
                ('tutorial', models.CharField(max_length=250)),
                ('difficulty', models.IntegerField()),
                ('encrypt_func', models.CharField(max_length=250)),
                ('encrypted_message', models.CharField(max_length=250)),
            ],
        ),
    ]
