# Generated by Django 5.2 on 2025-05-24 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_gamesetup'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_no', models.IntegerField(unique=True)),
                ('continent', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=250)),
                ('region', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('district', models.CharField(max_length=250)),
                ('area', models.CharField(max_length=250)),
                ('street', models.CharField(max_length=250)),
                ('coordinates', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='gamesetup',
            unique_together={('challenge_id', 'stage')},
        ),
        migrations.AddField(
            model_name='gamesetup',
            name='game_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.gameadmin'),
        ),
    ]
