# Generated by Django 5.2.1 on 2025-05-25 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_gameadmin_alter_gamesetup_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamehistory',
            name='won',
            field=models.BooleanField(default=False),
        ),
    ]
