# Generated by Django 5.2.1 on 2025-05-25 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_gamehistory_won'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='game_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.gamehistory'),
        ),
    ]
