# Generated by Django 5.2.1 on 2025-05-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_gamesession_game_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamehistory',
            name='challenge_id',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
