# Generated by Django 5.2.1 on 2025-05-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_gamehistory_challenge_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameadmin',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the challenge that will be shown in the selection menu'),
        ),
    ]
