# Generated by Django 5.2 on 2025-05-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_gameadmin_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameadmin',
            name='title',
            field=models.CharField(default='default', max_length=250),
            preserve_default=False,
        ),
    ]
